In [1]:
matrix=[[1,2,3,4],
        [5,6,7,8],
        [9,21,12,34],
        [11,22,33,44]]
for row in matrix:
    for element in row :
        print(element, end=' ')
    print()

1 2 3 4 
5 6 7 8 
9 21 12 34 
11 22 33 44 


In [3]:
lst=[]
for i in range(10):
    lst.append(int(input ("enter the number ")))

for j in lst:
    if j%2!=0:
        print("odd numbers ", j)


odd numbers  143
odd numbers  45


In [4]:
class Employee:
    def __init__(self):
        self.name="vinayak"
        self.position='data analyst'
        self.sallary=50000

    def  anual_sal(self):
        result=self.sallary*12
        return result
    
a=Employee()
a.anual_sal()


600000

In [8]:
import csv 
try :
    with open("C:/Users/Administrator/Desktop/citric.csv","r")as file :
        csv_reader=csv.reader(file)
        column_index=2
        for row in csv_reader:
            try:
                column_value=row[column_index]
                print(column_value)
            except IndexError:
                print(f"colum not found in row :{row}")
            except FileNotFoundError:
                print("error : the specified file was not found ")
except FileNotFoundError:
    print("error the specified file was not found ")

except Exception as e:
    print(f"an erre occured :{str(e)}")

Output
Lemon
Lemon
Lemon
Lemon
Lemon
Lemon
Lemon
Lemon
Lemon
Orange
Orange
Orange
Orange
Orange
Orange
Orange
Orange
Orange
Orange


In [12]:
# Program to multiply two matrices (vectorized implementation)

# Program to multiply two matrices (vectorized implementation)
import numpy as np
# take a 3x3 matrix
A = [[12, 7, 3],
	[4, 5, 6],
	[7, 8, 9]]

# take a 3x4 matrix
B = [[5, 8, 1, 2],
	[6, 7, 3, 0],
	[4, 5, 9, 1]]

# result will be 3x4

result= [[0,0,0,0],
		[0,0,0,0],
		[0,0,0,0]]

result = np.dot(A,B)

for r in result:
	print(r)


[114 160  60  27]
[74 97 73 14]
[119 157 112  23]
