In [ ]:
import array as ar 
arr=ar.array("i",[1,2,3,4])
print(arr)

array('i', [1, 2, 3, 4])


In [ ]:
# import array as ar
arr = ar.array("i", [1, 2, 3, 4])
print(arr)


array('i', [1, 2, 3, 4])


In [ ]:
import array as ar
arr=ar.array("i",[1,2,3,5,6])
ap=arr[1:4]
print(ap)


array('i', [2, 3, 5])


In [ ]:
import array as ar
a=ar.array("u",["u","a","b","c","d","e"])
for i in a:
    print(i,"\n")

u 

a 

b 

c 

d 

e 



Adding two array

In [2]:
import array as ar
arr=ar.array('i',[1,2,3,35])
arr2=ar.array(arr.typecode,(a * 3 for a in arr ))
print(arr2)

array('i', [3, 6, 9, 105])


In [ ]:
import array as ar

arr = ar.array('i', [1, 2, 3, 35])
arr2 = ar.array("i", (a * 3 for a in arr))

print(arr2)


array('i', [3, 6, 9, 105])


retrieve the element of an array using array index

In [ ]:
import array as ar
a=ar.array("i",[1,2,3,4,5])
for i in range(len(a)):
    print(a[i],end=" ")# end space gives print data in same line 

1 2 3 4 5 

retrieve the element of an array using while loop

In [ ]:
import array as ar
a=ar.array("i",[1,2,3,4,5])
n=len(a)
i=0
while i<n:
    print(a[i],end=" ")
    i+=1


1 2 3 4 5 

Slicing operation 

In [5]:
import array as ar
a=ar.array("i",[2,1,6,3,4,5])
print(a[2:4])
print(a[:4])
print(a[4:])
print(a[-4:])
print(a[ :-1])# check seriosly
print(a[0:4:2])



array('i', [6, 3])
array('i', [2, 1, 6, 3])
array('i', [4, 5])
array('i', [6, 3, 4, 5])
array('i', [2, 1, 6, 3, 4])
array('i', [2, 6])


Array methods

In [3]:
import array as ar
a=ar.array("i",[1,2,3,4,5])
a.append(30)
print(a)
print(a.count(1))#count the value of occurance
lst=[10,20,30,40,50]
a.fromlist(lst)#appending list value to array
print(a)
print("printing a index  value of  20 number =",a.index(20))
a.insert(7,2)
print("iserting the 2 value in index 7  ",a)
a.pop(5)#here we specifieng index value 
print("removing index(5) value(30) 30 is removing ",a)
a.remove(2)#remove method is removing the first ocurance value here
# we are specifieng value in array 
print(",remove method ",a)
#converting array to list
c=a.tolist()
print("converting array to to list",c)
#converting array to string



array('i', [1, 2, 3, 4, 5, 30])
1
array('i', [1, 2, 3, 4, 5, 30, 10, 20, 30, 40, 50])
printing a index  value of  20 number = 7
iserting the 2 value in index 7   array('i', [1, 2, 3, 4, 5, 30, 10, 2, 20, 30, 40, 50])
removing index(5) value(30) 30 is removing  array('i', [1, 2, 3, 4, 5, 10, 2, 20, 30, 40, 50])
,remove method  array('i', [1, 3, 4, 5, 10, 2, 20, 30, 40, 50])
converting array to to list [1, 3, 4, 5, 10, 2, 20, 30, 40, 50]


storing student marks and total marks percentage

In [ ]:
import array as ar

lst = [int(i) for i in input("Enter the student marks (comma-separated): ").split(",")]
print(lst)
marks = ar.array("i", lst)
total_marks = sum(marks)
print("Total marks:", total_marks)
percentage=total_marks*100/600
print(percentage)




[50, 50, 50, 50, 50, 50, 50, 50, 50, 50]
Total marks: 500
83.33333333333333


working with numpy with array

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,56])# single dimenstional array
print(arr)

[ 1  2  3  4 56]


#line space in numpy

In [ ]:
import numpy as np
# number start with 0 and end with 10 then 0 to  10 digits are equally divided into 5 digits 
# like equally 5 that is 0,2.5,5,7.5,10
arr=np.linspace(0,10,5)
print(arr)
ar2=np.logspace(0,10,5)
print(ar2)


[ 0.   2.5  5.   7.5 10. ]
[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10]


In [ ]:
ar=np.arange(4,10)
print(ar)
one=np.ones(6).reshape(2,3)
zers=np.zeros(10)
print(zers)
print(one)
# print(ar)

[4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


Comparing arrays and "any()",and "all()" function

In [ ]:
import numpy as np
arr1=np.array([10,20,30,78,95])
arr2=np.array([10,50,100,78,90])

c=arr1==arr2
print("comparing each value in both array",c)
d=arr1>arr2
print("comparing each value in arr1 and arr2",d)
print("any on element is bigger in arr1 it will print true:",any(c))
# all method :all arr1 is greater than all arr2 elment  then it will print true oter wise falls
print(all(c))





comparing each value in both array [ True False False  True False]
comparing each value in arr1 and arr2 [False False False False  True]
any on element is bigger in arr1 it will print true: True
False


Where function

In [ ]:
import numpy as np
ar=np.array([12,3,4,54,5])
#it will check each elemet is mod of 2==0 then it will that store int c or if condition 
# falls then it will store o to c
c=np.where(ar%2==0,ar,0)
print(c)
ar2

[12  0  4 54  0]


In [ ]:
import array as ar
import numpy as np
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(a)
print("length of array ",len(a))
for i in range(len(a)):
    for j in range(len(a)):
        print(a[i][j],end="\n")
# print(a[0][0])
print(a[0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
length of array  3
1
2
3
4
5
6
7
8
9
[1 2 3]


In [ ]:
import array as ar
import numpy as np
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(a[0,:])
print(a[:,0])
print(a[0][0])

[1 2 3]
[1 4 7]
1


3D array

In [ ]:
import array as ar
import numpy as np
# here two arrays are there that is 0 and 1  inside each array having two rows 3 column simmilar to 1 sta array
a=np.array([[[1,2,3],
             [4,5,6]] ,
            [[7,8,9],
             [10,11,12]]])
print(a.ndim)
print(a[0][1][1])
print(a[0][0])

3
5
[1 2 3]


Matrix

In [16]:
import array as ar
import numpy as np
arr=ar.array("i",[1,2],[5,78])
a=ar.matrix(arr)
print(a,type(a))
# array works only single dimension  so this is error

TypeError: array() takes at most 2 arguments (3 given)

In [20]:
import array as ar
import numpy as np
arr=np.array(([1,2],[5,78]))# two parentisis involved 
a=np.matrix(arr)
print(a,type(a))
# array works only single dimension  so this is error

[[ 1  2]
 [ 5 78]] <class 'numpy.matrix'>


In [36]:
import array as ar
import numpy as np
arr=np.array(([1,2],[5,78]))# two parentisis involved 
a=np.matrix(arr)
print(a,type(a))

print("printing diagonal element")
print(a.diagonal())# printing diagonal element
print("printing maximum value inmatrix",a.max())
print("printing minimum value",a.min())
print("printing sum of the matrix",a.sum())
print("printing product column wise = ",a.prod(0))#colum wise should write prod(0)
# like 5X1 and 78X2
print("printing product of matrix row wise =",a.prod(1))#row wise should write prod(1)





[[ 1  2]
 [ 5 78]] <class 'numpy.matrix'>
printing diagonal element
[[ 1 78]]
printing maximum value inmatrix 78
printing minimum value 1
printing sum of the matrix 86
printing product column wise =  [[  5 156]]
printing product of matrix row wise = [[  2]
 [390]]


Sorting matrix

In [54]:
# import numpy as np
m=np.matrix([[4,5,1],[9,7,3]])
# print(m)
print(np.sort(m))# by default axis become one it arrangig the elment in asending order
#  from row wise
print("------------------------------------------------------------------")
print("printig the element in asending order from colum wise because axis=0 =","\n",
      np.sort(m,axis=0)) 

[[1 4 5]
 [3 7 9]]
------------------------------------------------------------------
printig the element in asending order from colum wise because axis=0 = 
 [[4 5 1]
 [9 7 3]]


In [64]:
import numpy as np
class a:
    m=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
    print("printing original matrix","\n",m)
    print("printing the transpose matrix ", "\n" , m.transpose())

printing original matrix 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
printing the transpose matrix  
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


Accept the matrix from keybord 

1,2,3 4,5,6


In [139]:
list1=np.array(["1,2,3"])
print(list1)
li=[]
for i in list1:
    a=i.split(",")
    print(a)


for i in a:
    ab=int(i)
    print(ab)
    li.append(ab)
arra3=np.array(li)
print(arra3)
for i in arra3:
    print(i)




['1,2,3']
['1', '2', '3']
1
2
3
[1 2 3]
1
2
3


In [112]:
list1=["1,2,3"]
li=[]
for i in list1:
    a=i.split(",")
    
print(a)
for i in a:
    li.append(int(i))
li

['1', '2', '3']


[1, 2, 3]